feat: add pagination for list appeal and list grant
goto/guardian pull request #60
Opened 2023-08-22 03:52 UTC by lifosmin

2023-08-22 04:29 UTC, rahmatrhd requested changes

2023-08-22 04:29 UTC, rahmatrhd commented on buf.gen.yaml
> -      - lang=go
let's revert this file to the original

2023-08-22 04:29 UTC, rahmatrhd commented on api/handler/v1beta1/grant.go
>  	}
I think we're missing on ListUserGrants

2023-08-28 05:24 UTC, bsushmith commented on internal/store/postgres/appeal_repository_test.go
>  }
Can you rename the test cases or make them table tests if needed?

2023-08-28 05:24 UTC, bsushmith commented on internal/store/postgres/grant_repository_test.go
> +			Size:   1,
Can you rename the test cases or make them table tests if needed?

2023-08-29 03:26 UTC, rahmatrhd approved these changes
LGTM

2023-08-29 03:30 UTC, merged