Bug: Fix Grants bug
goto/guardian pull request #65
Opened 2023-09-04 10:15 UTC by lifosmin

2023-09-05 02:49 UTC, rahmatrhd commented on internal/store/postgres/grant_repository.go
> +	db = db.Joins("Resource")
please add test cases

2023-09-05 02:50 UTC, rahmatrhd requested changes

2023-09-05 02:50 UTC, rahmatrhd commented on __debug_bin4270744017
this should be removed 😄

2023-09-05 03:57 UTC, lifosmin commented on internal/store/postgres/grant_repository_test.go
I think this test would check if there is error on accessing the db which was the problem from previous case.

2023-09-07 04:07 UTC, rahmatrhd approved these changes

2023-09-12 06:53 UTC, merged